parameters:
  - name: serviceConnection
    type: string

  - name: environment
    type: string

jobs:
  - deployment: deployRolesJob
    displayName: 'Deploy roles - ${{ parameters.environment}}'
    environment: pac-roles-${{ parameters.environment }}
    variables:
      PAC_INPUT_FOLDER: "$(Pipeline.Workspace)"
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - download: current
              artifact: plans-${{ parameters.environment }}
            - task: AzurePowerShell@5
              name: deployStep
              displayName: Deploy policy
              inputs:
                azureSubscription: ${{ parameters.serviceConnection }}
                pwsh: true
                azurePowerShellVersion: LatestVersion
                ScriptPath: "Scripts/Deploy/Deploy-RolesPlan.ps1" 
                ScriptArguments: 
                  -pacEnvironmentSelector ${{ parameters.environment }}
                  -InformationAction Continue