name: Policy_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

# trigger: 
# pr:

variables: 
  PAC_OUTPUT_FOLDER: ./Output
  PAC_DEFINITIONS_FOLDER: ./Definitions

  developmentServiceConnection: 'sc-epac-dev'
  productionServiceConnection: 'sc-epac-dev'

stages:
  - stage: plan
    displayName: Plan
    jobs:
      - template: templates/jobs-build-deployment-plan.yml
        parameters:
          serviceConnection: $(developmentServiceConnection)
          jobName: 'jobPlanDevelopment'
          environment: 'development'
          publishPlan: false

      - template: templates/jobs-build-deployment-plan.yml
        parameters:
          serviceConnection: $(productionServiceConnection)
          jobName: 'jobPlanProduction'
          environment: 'production'
          publishPlan: false       