name: Policy_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
# pr:

variables: 
  PAC_OUTPUT_FOLDER: ./Output
  PAC_DEFINITIONS_FOLDER: ./Definitions

  developmentServiceConnection: 'sc-epac-dev'
  productionServiceConnection: 'sc-epac-dev'

stages:
  - stage: plan
    displayName: Plan
    jobs:
      - template: templates/job-build-deployment-plan.yml
        parameters:
          serviceConnection: $(developmentServiceConnection)
          jobName: 'jobPlanDevelopment'
          environment: 'ePAC-Test'
          publishPlan: false

      - template: templates/job-build-deployment-plan.yml
        parameters:
          serviceConnection: $(productionServiceConnection)
          jobName: 'jobPlanProduction'
          environment: 'TenantProd'
          publishPlan: false       